[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache, must-revalidate"